latest changes

diff --git a/usr/bin/gg b/usr/bin/gg
--- a/usr/bin/gg
+++ b/usr/bin/gg
@@ -4,26 +4,30 @@
 # jesse.chandler@suse.com
 # Supportconfig/hb_report log filter & highlighter
 # Usage: gg [options] [file]
-# GREP_COLOR="$COLOR" $grepsearch|$grepfilter -f </var/lib/gg-highlight/file containing patterns. e.g. '^.*.*$|$'>
+# GREP_COLORS="$COLOR" $grepsearch|$grepfilter -f </var/lib/gg-highlight/file containing patterns. e.g. '^.*.*$|$'>
 
 ##TODO remove binary chars on the fly (Nasty bits added when syslog starts sometimes).
 #This is the manual way to clean those up.
 #cat messages|tr -cd '\11\12\15\40-\176' > messages.new && mv -f messages.new messages
 ##TODO add bash completion
 
-VERSION=1.2.2
+VERSION=1.3.0
 
 # Coloring
-RED='1;37;41'
-YELLOW='01;33'
-GREEN='01;32'
+RED='mt=1;37;41'
+YELLOW='mt=01;33'
+GREEN='mt=01;32'
+WHITERED='mt=47;1;31'
+PURPLE='mt=01;1;35'
 # Commands
 grepsearch='grep -E --text --color=always --line-buffered'
 grepfilter='grep --text --line-buffered -Ev'
 # Lists/Arrays
 redpatterns=("general-red" "ha-red" "sap-red" "caas-red" "hacib-red" "drbd-red")
-yellowpatterns=("general-yellow" "ha-yellow" "sap-yellow" "supportconfig-yellow" "hacib-yellow" "drbd-yellow")
-greenpatterns=("general-green" "ha-green" "hacib-green" "sap-green" "drbd-green")
+yellowpatterns=("general-yellow" "ha-yellow" "sap-yellow" "caas-yellow" "supportconfig-yellow" "hacib-yellow" "drbd-yellow")
+greenpatterns=("general-green" "ha-green" "hacib-green" "corosynclog-green" "sap-green" "caas-green" "drbd-green")
+whitepatterns=("rpm-white")
+purplepatterns=("ha-status-purple")
 filters=("filter-general" "filter-ha" "filter-caas" "filter-sap" "filter-soc")
 experimental=("filter-test" "filter-disk" "filter-systemd")
 products=("ha" "caas" "sap" "soc")
@@ -32,12 +36,12 @@ FILTER=false
 EXPERIMENTAL=false
 
 function usage() {
-	echo "Usage: gg [OPTION]... <FILE>"
-	echo "-i, --ignore, -f, --filter     (default: false) Enable filtering"
+	echo "Usage: gg [OPTION]... [FILE]"
+	echo "-i, --ignore, -f, --filter 			Enable filtering"
 	echo "-v, --version 					Display version"
 	echo "-h, --help 					Show this list"
-	echo "-d, --disable ["${products[@]}"](default: none)  Exclude product patterns"
-	echo "-e, --experimental	       (default: false) Enable experimental features"
+	echo "-d, --disable ["${products[@]}"]			disable product filter"
+	echo "-e, --experimental				enable experimental features"
 }
 
 function display_version() {
@@ -64,6 +68,13 @@ function reduce-arrays() {
                 if [[ "${greenpatterns[$i]}" = "$1"* ]]
                 then
                         unset "greenpatterns[$i]"
+                fi
+        done
+        for i in "${!whitepatterns[@]}"
+        do
+                if [[ "${whitepatterns[$i]}" = "$1"* ]]
+                then
+                        unset "whitepatterns[$i]"
                 fi
         done
         for i in "${!filters[@]}"
@@ -125,7 +136,6 @@ fi
 # Check for arguments
 if [ $# -eq 0 ]; then
     echo "No arguments provided"
-    usage
     exit 1
 fi
 
@@ -137,7 +147,7 @@ if [[ ! -e $file_arg ]]; then
 fi
 
 # Don't include hacib stuff unless "cib" is in the name of the file
-if  ! echo "$file_arg" | grep -E "ha.txt|*cib*"; then
+if  ! echo "$file_arg" | grep -E "cib*|ha.txt|pe-input-*|pe-warn-*|pe-error-*|plugin-ha_sap.txt|corosync.conf|configure_show.txt"; then
         reduce-arrays "hacib"
 fi
 
@@ -147,7 +157,7 @@ function iterate-redhighlights() {
 	do
 		greplist+=( -f /var/lib/gg-highlight/"${i}".txt)
 	done
-	LANG=C LC_ALL=C GREP_COLOR="$RED" $grepsearch "${greplist[@]}"
+	LANG=C LC_ALL=C GREP_COLORS="$RED" $grepsearch "${greplist[@]}"
 }
 
 function iterate-yellowhighlights() {
@@ -156,7 +166,7 @@ function iterate-yellowhighlights() {
 	do
 		greplist+=( -f /var/lib/gg-highlight/"${i}".txt)
 	done
-	LANG=C LC_ALL=C GREP_COLOR="$YELLOW" $grepsearch "${greplist[@]}"
+	LANG=C LC_ALL=C GREP_COLORS="$YELLOW" $grepsearch "${greplist[@]}"
 }
 
 function iterate-greenhighlights() {
@@ -165,8 +175,28 @@ function iterate-greenhighlights() {
 	do
 		greplist+=( -f /var/lib/gg-highlight/"${i}".txt)
 	done
-	LANG=C LC_ALL=C GREP_COLOR="$GREEN" $grepsearch "${greplist[@]}"
+	LANG=C LC_ALL=C GREP_COLORS="$GREEN" $grepsearch "${greplist[@]}"
 }
+
+function iterate-whitehighlights() {
+        greplist=()
+        for i in "${whitepatterns[@]}"
+        do
+                greplist+=( -f /var/lib/gg-highlight/"${i}".txt)
+        done
+        LANG=C LC_ALL=C GREP_COLORS="$WHITERED" $grepsearch "${greplist[@]}"
+}
+
+function iterate-purplehighlights() {
+        greplist=()
+        for i in "${purplepatterns[@]}"
+        do
+                greplist+=( -f /var/lib/gg-highlight/"${i}".txt)
+        done
+        LANG=C LC_ALL=C GREP_COLORS="$PURPLE" $grepsearch "${greplist[@]}"
+}
+
+
 
 function iterate-filters() {
 	if [[ $FILTER = true ]]; then
@@ -197,9 +227,11 @@ function iterate-experimental() {
 function allyourlogsarebelongtome() {
 	iterate-filters |\
 	iterate-experimental |\
+	iterate-purplehighlights |\
 	iterate-redhighlights |\
 	iterate-yellowhighlights |\
-	iterate-greenhighlights
+	iterate-greenhighlights |\
+	iterate-whitehighlights 
 }
 
 cat "$file_arg" | allyourlogsarebelongtome | less
